export const restaurants = [
  {
    id: 'r1',
    name: '阳光小馆',
    category: '中式快餐',
    rating: 4.8,
    avg: 32,
    fee: 6,
    description: '经典快餐组合，营养均衡，适合学生与上班族。',
    opening: '上午10:30 - 晚上21:30',
    delivery: '满20元起送，预计30分钟送达',
    menu: [
      { id: 'd101', name: '宫保鸡丁', description: '微辣鸡丁，花生香脆，经典川菜', price: 28, sales: 328, rating: 96, calories: 350, tags: ['招牌', '热销', '辣'] },
      { id: 'd102', name: '番茄炒蛋', description: '家常风味，酸甜开胃，老少皆宜', price: 22, sales: 456, rating: 94, calories: 220, tags: ['素食'] },
      { id: 'd103', name: '红烧狮子头', description: '汤汁浓郁，软糯入味，肉质鲜嫩', price: 36, sales: 189, rating: 97, calories: 420, tags: ['招牌'] },
      { id: 'd104', name: '青菜豆腐汤', description: '清爽配餐，滋补不油腻，清淡可口', price: 12, sales: 234, rating: 92, calories: 80, tags: ['素食'] },
    ],
  },
  {
    id: 'r2',
    name: '小镇披萨屋',
    category: '西式轻食',
    rating: 4.5,
    avg: 48,
    fee: 0,
    description: '手工披萨与意面，满足多种口味。',
    opening: '上午11:00 - 晚上22:00',
    delivery: '全国配送，预计40分钟送达',
    menu: [
      { id: 'd201', name: '玛格丽特披萨', description: '经典芝士与番茄酱，手工薄底', price: 48, sales: 267, rating: 95, calories: 580, tags: ['招牌', '热销'] },
      { id: 'd202', name: '培根意面', description: '烟熏培根搭配奶油酱，香浓可口', price: 42, sales: 156, rating: 93, calories: 450, tags: [] },
      { id: 'd203', name: '凯撒沙拉', description: '新鲜生菜与香脆面包丁，健康之选', price: 28, sales: 198, rating: 94, calories: 320, tags: ['素食'] },
      { id: 'd204', name: '奶油蘑菇汤', description: '浓郁蘑菇风味，暖胃首选，口感丝滑', price: 18, sales: 312, rating: 96, calories: 180, tags: ['热销'] },
    ],
  },
  {
    id: 'r3',
    name: '健康轻食',
    category: '沙拉 / 养生',
    rating: 4.7,
    avg: 36,
    fee: 5,
    description: '低脂轻食，适合减脂族与健康饮食。',
    opening: '上午09:30 - 晚上20:30',
    delivery: '满30元起送，预计35分钟送达',
    menu: [
      { id: 'd301', name: '鸡胸肉凯撒沙拉', description: '高蛋白低脂，清爽饱腹，健身必备', price: 38, sales: 423, rating: 98, calories: 380, tags: ['招牌', '热销'] },
      { id: 'd302', name: '牛油果蔬菜卷', description: '丰富蔬菜与香浓牛油果，营养均衡', price: 32, sales: 289, rating: 95, calories: 290, tags: ['素食'] },
      { id: 'd303', name: '藜麦水果碗', description: '营养均衡，酸甜可口，轻食首选', price: 30, sales: 178, rating: 94, calories: 250, tags: ['素食'] },
      { id: 'd304', name: '柠檬姜茶', description: '暖身解腻，清新不甜，养生佳品', price: 14, sales: 512, rating: 97, calories: 60, tags: ['热销', '素食'] },
    ],
  },
];